/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.8.22"
}

group = "net.pterodactylus.freenet"
version = "0.0.1-SNAPSHOT"

kotlin {
    jvmToolchain(8)
}

repositories {
    mavenCentral()
    maven("https://maven.pterodactylus.net/")
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.freenetproject:fred:0.7.5.1497")

	testImplementation(platform("org.junit:junit-bom:5.9.3"))
	testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.mockito.kotlin:mockito-kotlin:4.1.0")
}

tasks.test {
	useJUnitPlatform()
}
